# Generated by Django 4.2 on 2023-04-08 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoiceDate", models.DateField()),
                ("dueDate", models.DateField()),
                ("totalAmount", models.FloatField()),
                ("dueAmount", models.FloatField()),
                ("advancePercent", models.IntegerField()),
                ("workCompleted", models.BooleanField()),
                ("note", models.CharField(max_length=200)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoiceClient",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoiceUser",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("itemid", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=200)),
                ("quantity", models.IntegerField()),
                ("price", models.FloatField()),
                ("discount", models.IntegerField()),
                ("tax", models.FloatField()),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="invoices.invoice",
                    ),
                ),
            ],
        ),
    ]
