version: '1'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1-arm64
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.13.1-arm64
    container_name: logstash
    command: logstash -f ./config/logstash.conf
    links:
      - elasticsearch
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/config/logstash.conf:ro,Z
      - ../backend/logs/debug.log:/usr/share/logstash/logs/debug.log

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1-arm64
    container_name: kibana
    ports:
      - "5601:5601"