version: '1'
services:
  change-vol-ownership:
    # We can use any image we want as long as we can chown
    image: ubuntu
    # Need a user priviliged enough to chown
    user: "root"
    # Specify the group in question
    group_add:
      - '1000'
    volumes:
      # The volume to chown
      - ../backend/logs/debug.log:/tmp/change-ownership
    command: chown -R 1000:1000 /tmp/change-ownership

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1-arm64
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    user: "1000:1000"
    image: docker.elastic.co/logstash/logstash:7.13.1-arm64
    container_name: logstash
    command: logstash -f ./config/logstash.conf
    links:
      - elasticsearch
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/config/logstash.conf:ro,Z
      - ../backend/logs/debug.log:/usr/share/logstash/logs/debug.log:rw,z
    depends_on:
      change-vol-ownership:
        # Wait for the ownership to change
        condition: service_completed_successfully

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1-arm64
    container_name: kibana
    ports:
      - "5601:5601"